name: 🐛 Bug Report
description: Report a bug or unexpected behavior in WinSentinel
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below so we can reproduce and fix it.

  - type: input
    id: version
    attributes:
      label: WinSentinel Version
      description: Which version are you running? (Check `WinSentinel.Cli --version` or the About dialog)
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of WinSentinel is affected?
      options:
        - Agent (Windows Service)
        - Dashboard (WPF App)
        - CLI
        - Installer
        - Audit Module
        - IPC / Named Pipes
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Windows Version
      options:
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 10 22H2
        - Windows 10 (older)
        - Windows Server 2022
        - Windows Server 2019
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Install WinSentinel via '...'
        2. Start the agent service
        3. Open the dashboard
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Error Output
      description: Paste any relevant log output, stack traces, or error messages. This will be automatically formatted as code.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context—screenshots, configuration details, whether running as admin, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I am running WinSentinel with administrator privileges
          required: false
