using System.Diagnostics;
using System.Text.Json;

namespace WinSentinel.Cli.ScheduledScans;

/// <summary>
/// Manages scheduled security scans via Windows Task Scheduler (schtasks.exe).
/// No license gate — this is a free feature.
/// </summary>
public static class ScheduleEngine
{
    private const string TaskNamePrefix = "WinSentinel_ScheduledAudit";
    private const string ResultsDirName = "scheduled-scans";

    public static string GetAppDataDir()
    {
        var appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        if (string.IsNullOrEmpty(appData))
            appData = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        return Path.Combine(appData, "WinSentinel");
    }

    public static string GetResultsDir()
    {
        var dir = Path.Combine(GetAppDataDir(), ResultsDirName);
        Directory.CreateDirectory(dir);
        return dir;
    }

    public static string GetConfigPath() => Path.Combine(GetAppDataDir(), "schedule-config.json");

    public static ScheduleConfig? LoadConfig()
    {
        var path = GetConfigPath();
        if (!File.Exists(path)) return null;
        try { return JsonSerializer.Deserialize<ScheduleConfig>(File.ReadAllText(path)); }
        catch { return null; }
    }

    public static void SaveConfig(ScheduleConfig config)
    {
        Directory.CreateDirectory(GetAppDataDir());
        File.WriteAllText(GetConfigPath(), JsonSerializer.Serialize(config, new JsonSerializerOptions { WriteIndented = true }));
    }

    /// <summary>
    /// Resolves the winsentinel CLI path on this machine.
    /// </summary>
    public static string ResolveCliPath()
    {
        if (!OperatingSystem.IsWindows()) return "winsentinel";
        try
        {
            var psi = new ProcessStartInfo("where", "winsentinel")
            {
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using var proc = Process.Start(psi);
            var output = proc?.StandardOutput.ReadToEnd().Trim() ?? "";
            proc?.WaitForExit(5000);
            var first = output.Split(Environment.NewLine, StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
            return string.IsNullOrEmpty(first) ? "winsentinel" : first;
        }
        catch { return "winsentinel"; }
    }

    public static string GetWrapperScriptPath() => Path.Combine(GetAppDataDir(), "scheduled-audit.ps1");

    private static string BuildWrapperScript(string cliPath, ScheduleConfig config)
    {
        var resultsDir = GetResultsDir().Replace("\\", "\\\\");
        var autoFixFlag = config.AutoFix ? " --fix" : "";
        var modulesFlag = !string.IsNullOrEmpty(config.Modules) ? $" --modules {config.Modules}" : "";

        return $@"# WinSentinel — Scheduled Audit Script
# Auto-generated by winsentinel schedule. Do not edit manually.
$ErrorActionPreference = ""SilentlyContinue""
$resultsDir = ""{resultsDir}""
if (!(Test-Path $resultsDir)) {{ New-Item -ItemType Directory -Path $resultsDir -Force | Out-Null }}

$timestamp = Get-Date -Format ""yyyy-MM-dd_HH-mm-ss""
$outFile = Join-Path $resultsDir ""scan_$timestamp.json""

try {{
    $output = & ""{cliPath.Replace("\\", "\\\\")}"" --audit --json --quiet{autoFixFlag}{modulesFlag} 2>&1
    $output | Out-File -FilePath $outFile -Encoding utf8

    # Prune old results (keep last 90 days)
    Get-ChildItem $resultsDir -Filter ""scan_*.json"" | Where-Object {{ $_.LastWriteTime -lt (Get-Date).AddDays(-90) }} | Remove-Item -Force
}} catch {{
    ""[$timestamp] ERROR: $_"" | Out-File -FilePath (Join-Path $resultsDir ""scan_$timestamp.log"") -Encoding utf8
}}
";
    }

    /// <summary>Create or update a scheduled scan task.</summary>
    public static (bool Ok, string Message) CreateSchedule(ScheduleConfig config)
    {
        if (!OperatingSystem.IsWindows())
            return (false, "Scheduled scans require Windows Task Scheduler.");

        var validCadences = new[] { "hourly", "daily", "weekly" };
        if (!validCadences.Contains(config.Cadence))
            return (false, $"Invalid cadence \"{config.Cadence}\". Use: hourly, daily, weekly.");

        if (!string.IsNullOrEmpty(config.Time) && !System.Text.RegularExpressions.Regex.IsMatch(config.Time, @"^\d{2}:\d{2}$"))
            return (false, $"Invalid time format \"{config.Time}\". Use HH:MM (24-hour).");

        config.CreatedAt = DateTime.UtcNow.ToString("o");

        // Write wrapper script
        var cliPath = ResolveCliPath();
        var script = BuildWrapperScript(cliPath, config);
        Directory.CreateDirectory(GetAppDataDir());
        File.WriteAllText(GetWrapperScriptPath(), script);

        // Build schtasks args
        var taskName = config.TaskName ?? TaskNamePrefix;
        var args = $"/Create /TN \"{taskName}\" /TR \"powershell.exe -NoProfile -WindowStyle Hidden -File \\\"{GetWrapperScriptPath()}\\\"\" /F /RL HIGHEST";

        args += config.Cadence switch
        {
            "hourly" => " /SC HOURLY",
            "weekly" => $" /SC WEEKLY /ST {config.Time ?? "03:00"}" + (!string.IsNullOrEmpty(config.DayOfWeek) ? $" /D {config.DayOfWeek}" : ""),
            _ => $" /SC DAILY /ST {config.Time ?? "03:00"}"
        };

        try
        {
            var psi = new ProcessStartInfo("schtasks.exe", args)
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using var proc = Process.Start(psi)!;
            proc.WaitForExit(15000);
            if (proc.ExitCode != 0)
            {
                var err = proc.StandardError.ReadToEnd();
                return (false, $"Failed to create scheduled task. Run as Administrator.\n{err}");
            }
        }
        catch (Exception ex)
        {
            return (false, $"Failed to create scheduled task: {ex.Message}");
        }

        SaveConfig(config);
        return (true, $"Scheduled scan created: {config.Cadence} at {config.Time ?? "every hour"}{(!string.IsNullOrEmpty(config.DayOfWeek) ? $" on {config.DayOfWeek}" : "")}{(config.AutoFix ? " (auto-fix enabled)" : "")}");
    }

    /// <summary>Remove the scheduled scan task.</summary>
    public static (bool Ok, string Message) RemoveSchedule()
    {
        if (!OperatingSystem.IsWindows())
            return (false, "Not on Windows.");

        var config = LoadConfig();
        var taskName = config?.TaskName ?? TaskNamePrefix;

        try
        {
            var psi = new ProcessStartInfo("schtasks.exe", $"/Delete /TN \"{taskName}\" /F")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using var proc = Process.Start(psi)!;
            proc.WaitForExit(10000);
            if (proc.ExitCode != 0)
                return (false, "No scheduled scan task found or failed to remove.");
        }
        catch (Exception ex)
        {
            return (false, $"Failed to remove task: {ex.Message}");
        }

        var scriptPath = GetWrapperScriptPath();
        if (File.Exists(scriptPath)) File.Delete(scriptPath);
        var configPath = GetConfigPath();
        if (File.Exists(configPath)) File.Delete(configPath);

        return (true, $"Scheduled scan task \"{taskName}\" removed.");
    }

    /// <summary>Get current schedule status.</summary>
    public static (bool Ok, bool Active, string Message, ScheduleConfig? Config) GetStatus()
    {
        var config = LoadConfig();
        if (config == null)
            return (true, false, "No scheduled scan configured. Use `winsentinel schedule create` to set one up.", null);

        var taskName = config.TaskName ?? TaskNamePrefix;
        string? nextRun = null;

        if (OperatingSystem.IsWindows())
        {
            try
            {
                var psi = new ProcessStartInfo("schtasks.exe", $"/Query /TN \"{taskName}\" /FO CSV /NH")
                {
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };
                using var proc = Process.Start(psi)!;
                var output = proc.StandardOutput.ReadToEnd().Trim();
                proc.WaitForExit(10000);
                var parts = output.Split("\",\"");
                if (parts.Length >= 2) nextRun = parts[1].Trim('"');
            }
            catch
            {
                return (true, false, "Schedule config exists but task not found in Task Scheduler.", config);
            }
        }

        var msg = $"Scheduled: {config.Cadence} at {config.Time ?? "every hour"}{(!string.IsNullOrEmpty(config.DayOfWeek) ? $" ({config.DayOfWeek})" : "")} | Auto-fix: {(config.AutoFix ? "on" : "off")}{(nextRun != null ? $" | Next run: {nextRun}" : "")}";
        return (true, true, msg, config);
    }

    /// <summary>List recent scheduled scan results.</summary>
    public static List<ScheduleResult> ListResults(int limit = 10)
    {
        var dir = GetResultsDir();
        var files = Directory.GetFiles(dir, "scan_*.json")
            .OrderByDescending(f => f)
            .Take(limit)
            .ToList();

        var results = new List<ScheduleResult>();
        foreach (var f in files)
        {
            try
            {
                var json = File.ReadAllText(f);
                using var doc = JsonDocument.Parse(json);
                var root = doc.RootElement;
                results.Add(new ScheduleResult
                {
                    File = Path.GetFileName(f),
                    Score = root.TryGetProperty("score", out var s) ? s.GetInt32() : null,
                    Grade = root.TryGetProperty("grade", out var g) ? g.GetString() : null,
                    FindingsCount = root.TryGetProperty("findings", out var fArr) && fArr.ValueKind == JsonValueKind.Array ? fArr.GetArrayLength() : null
                });
            }
            catch
            {
                results.Add(new ScheduleResult { File = Path.GetFileName(f) });
            }
        }
        return results;
    }
}

public class ScheduleResult
{
    public string File { get; set; } = "";
    public int? Score { get; set; }
    public string? Grade { get; set; }
    public int? FindingsCount { get; set; }
}
